# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1134, 740)
        Form.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.groupBoxShow = QtWidgets.QGroupBox(Form)
        self.groupBoxShow.setGeometry(QtCore.QRect(10, 10, 291, 721))
        self.groupBoxShow.setObjectName("groupBoxShow")
        self.BtOpenportShow = QtWidgets.QPushButton(self.groupBoxShow)
        self.BtOpenportShow.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.BtOpenportShow.setObjectName("BtOpenportShow")
        self.BtCloseportShow = QtWidgets.QPushButton(self.groupBoxShow)
        self.BtCloseportShow.setGeometry(QtCore.QRect(170, 20, 111, 31))
        self.BtCloseportShow.setObjectName("BtCloseportShow")
        self.BtSetTargetTemperature = QtWidgets.QPushButton(self.groupBoxShow)
        self.BtSetTargetTemperature.setGeometry(QtCore.QRect(110, 460, 171, 31))
        self.BtSetTargetTemperature.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtSetTargetTemperature.setObjectName("BtSetTargetTemperature")
        self.EditSetTargetTemperature = QtWidgets.QLineEdit(self.groupBoxShow)
        self.EditSetTargetTemperature.setGeometry(QtCore.QRect(20, 460, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditSetTargetTemperature.setFont(font)
        self.EditSetTargetTemperature.setText("")
        self.EditSetTargetTemperature.setAlignment(QtCore.Qt.AlignCenter)
        self.EditSetTargetTemperature.setObjectName("EditSetTargetTemperature")
        self.BtAutomaticGet = QtWidgets.QPushButton(self.groupBoxShow)
        self.BtAutomaticGet.setGeometry(QtCore.QRect(20, 420, 121, 31))
        self.BtAutomaticGet.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtAutomaticGet.setObjectName("BtAutomaticGet")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBoxShow)
        self.splitter_2.setGeometry(QtCore.QRect(20, 70, 171, 181))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.splitter_2)
        self.label_8.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.splitter_2)
        self.label_9.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(self.splitter_2)
        self.label.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.splitter_2)
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.BtAutomaticStop = QtWidgets.QPushButton(self.groupBoxShow)
        self.BtAutomaticStop.setGeometry(QtCore.QRect(160, 420, 111, 31))
        self.BtAutomaticStop.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtAutomaticStop.setObjectName("BtAutomaticStop")
        self.BtTemperatureValidation = QtWidgets.QPushButton(self.groupBoxShow)
        self.BtTemperatureValidation.setGeometry(QtCore.QRect(10, 640, 171, 31))
        self.BtTemperatureValidation.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtTemperatureValidation.setObjectName("BtTemperatureValidation")
        self.label_5 = QtWidgets.QLabel(self.groupBoxShow)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 171, 31))
        self.label_5.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBoxShow)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 171, 31))
        self.label_6.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.EditXAngle = QtWidgets.QLineEdit(self.groupBoxShow)
        self.EditXAngle.setGeometry(QtCore.QRect(200, 260, 81, 29))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditXAngle.setFont(font)
        self.EditXAngle.setText("")
        self.EditXAngle.setAlignment(QtCore.Qt.AlignCenter)
        self.EditXAngle.setObjectName("EditXAngle")
        self.EditYAngle = QtWidgets.QLineEdit(self.groupBoxShow)
        self.EditYAngle.setGeometry(QtCore.QRect(200, 300, 81, 29))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditYAngle.setFont(font)
        self.EditYAngle.setText("")
        self.EditYAngle.setAlignment(QtCore.Qt.AlignCenter)
        self.EditYAngle.setObjectName("EditYAngle")
        self.BtSetToZero = QtWidgets.QPushButton(self.groupBoxShow)
        self.BtSetToZero.setGeometry(QtCore.QRect(10, 550, 131, 31))
        self.BtSetToZero.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtSetToZero.setObjectName("BtSetToZero")
        self.BtAngleValidation = QtWidgets.QPushButton(self.groupBoxShow)
        self.BtAngleValidation.setGeometry(QtCore.QRect(20, 600, 121, 31))
        self.BtAngleValidation.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtAngleValidation.setObjectName("BtAngleValidation")
        self.BtStepValidation = QtWidgets.QPushButton(self.groupBoxShow)
        self.BtStepValidation.setGeometry(QtCore.QRect(150, 500, 131, 31))
        self.BtStepValidation.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtStepValidation.setObjectName("BtStepValidation")
        self.label_12 = QtWidgets.QLabel(self.groupBoxShow)
        self.label_12.setGeometry(QtCore.QRect(20, 500, 51, 31))
        self.label_12.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.EditStepTimes = QtWidgets.QLineEdit(self.groupBoxShow)
        self.EditStepTimes.setGeometry(QtCore.QRect(80, 500, 61, 31))
        self.EditStepTimes.setAlignment(QtCore.Qt.AlignCenter)
        self.EditStepTimes.setObjectName("EditStepTimes")
        self.splitter = QtWidgets.QSplitter(self.groupBoxShow)
        self.splitter.setGeometry(QtCore.QRect(200, 70, 81, 181))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.EditCH1Temperature = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditCH1Temperature.setFont(font)
        self.EditCH1Temperature.setText("")
        self.EditCH1Temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.EditCH1Temperature.setObjectName("EditCH1Temperature")
        self.EditCH2Temperature = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditCH2Temperature.setFont(font)
        self.EditCH2Temperature.setText("")
        self.EditCH2Temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.EditCH2Temperature.setObjectName("EditCH2Temperature")
        self.EditCH3Temperature = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditCH3Temperature.setFont(font)
        self.EditCH3Temperature.setText("")
        self.EditCH3Temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.EditCH3Temperature.setObjectName("EditCH3Temperature")
        self.EditCH4Temperature = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditCH4Temperature.setFont(font)
        self.EditCH4Temperature.setText("")
        self.EditCH4Temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.EditCH4Temperature.setObjectName("EditCH4Temperature")
        self.EditDiffTemperature = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditDiffTemperature.setFont(font)
        self.EditDiffTemperature.setText("")
        self.EditDiffTemperature.setAlignment(QtCore.Qt.AlignCenter)
        self.EditDiffTemperature.setObjectName("EditDiffTemperature")
        self.EditYAngle_X = QtWidgets.QLineEdit(self.groupBoxShow)
        self.EditYAngle_X.setGeometry(QtCore.QRect(200, 380, 81, 29))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditYAngle_X.setFont(font)
        self.EditYAngle_X.setText("")
        self.EditYAngle_X.setAlignment(QtCore.Qt.AlignCenter)
        self.EditYAngle_X.setObjectName("EditYAngle_X")
        self.EditXAngle_X = QtWidgets.QLineEdit(self.groupBoxShow)
        self.EditXAngle_X.setGeometry(QtCore.QRect(200, 340, 81, 29))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditXAngle_X.setFont(font)
        self.EditXAngle_X.setText("")
        self.EditXAngle_X.setAlignment(QtCore.Qt.AlignCenter)
        self.EditXAngle_X.setObjectName("EditXAngle_X")
        self.label_13 = QtWidgets.QLabel(self.groupBoxShow)
        self.label_13.setGeometry(QtCore.QRect(20, 380, 171, 31))
        self.label_13.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBoxShow)
        self.label_14.setGeometry(QtCore.QRect(20, 340, 171, 31))
        self.label_14.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.BtSetToZero_X = QtWidgets.QPushButton(self.groupBoxShow)
        self.BtSetToZero_X.setGeometry(QtCore.QRect(150, 550, 131, 31))
        self.BtSetToZero_X.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtSetToZero_X.setObjectName("BtSetToZero_X")
        self.groupBoxContorl = QtWidgets.QGroupBox(Form)
        self.groupBoxContorl.setGeometry(QtCore.QRect(300, 10, 801, 721))
        self.groupBoxContorl.setObjectName("groupBoxContorl")
        self.BtOpenportContorl = QtWidgets.QPushButton(self.groupBoxContorl)
        self.BtOpenportContorl.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.BtOpenportContorl.setObjectName("BtOpenportContorl")
        self.BtCloseportContorl = QtWidgets.QPushButton(self.groupBoxContorl)
        self.BtCloseportContorl.setGeometry(QtCore.QRect(130, 20, 111, 31))
        self.BtCloseportContorl.setObjectName("BtCloseportContorl")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBoxContorl)
        self.tabWidget.setGeometry(QtCore.QRect(10, 410, 861, 251))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_58 = QtWidgets.QLabel(self.tab_2)
        self.label_58.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label_58.setObjectName("label_58")
        self.ButtonGetSensorState = QtWidgets.QPushButton(self.tab_2)
        self.ButtonGetSensorState.setGeometry(QtCore.QRect(700, 190, 81, 23))
        self.ButtonGetSensorState.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonGetSensorState.setObjectName("ButtonGetSensorState")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 761, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_56 = QtWidgets.QLabel(self.layoutWidget)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_4.addWidget(self.label_56, 0, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.layoutWidget)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_4.addWidget(self.label_69, 0, 1, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.layoutWidget)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.gridLayout_4.addWidget(self.label_79, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_4.addWidget(self.label_50, 0, 3, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.layoutWidget)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.gridLayout_4.addWidget(self.label_61, 0, 4, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.gridLayout_4.addWidget(self.label_67, 0, 5, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.label_51, 0, 6, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.layoutWidget)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.gridLayout_4.addWidget(self.label_77, 0, 7, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.layoutWidget)
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.gridLayout_4.addWidget(self.label_75, 0, 8, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.layoutWidget)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_4.addWidget(self.label_64, 0, 9, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_4.addWidget(self.label_54, 0, 10, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.layoutWidget)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout_4.addWidget(self.label_82, 0, 11, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.layoutWidget)
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout_4.addWidget(self.label_83, 0, 12, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_4.addWidget(self.label_53, 0, 13, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.layoutWidget)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout_4.addWidget(self.label_71, 0, 14, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.layoutWidget)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout_4.addWidget(self.label_84, 0, 15, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.layoutWidget)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.gridLayout_4.addWidget(self.label_81, 0, 16, 1, 1)
        self.labelSensor1 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor1.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor1.setText("")
        self.labelSensor1.setObjectName("labelSensor1")
        self.gridLayout_4.addWidget(self.labelSensor1, 1, 0, 1, 1)
        self.labelSensor2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor2.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor2.setText("")
        self.labelSensor2.setObjectName("labelSensor2")
        self.gridLayout_4.addWidget(self.labelSensor2, 1, 1, 1, 1)
        self.labelSensor3 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor3.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor3.setText("")
        self.labelSensor3.setObjectName("labelSensor3")
        self.gridLayout_4.addWidget(self.labelSensor3, 1, 2, 1, 1)
        self.labelSensor4 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor4.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor4.setText("")
        self.labelSensor4.setObjectName("labelSensor4")
        self.gridLayout_4.addWidget(self.labelSensor4, 1, 3, 1, 1)
        self.labelSensor5 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor5.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor5.setText("")
        self.labelSensor5.setObjectName("labelSensor5")
        self.gridLayout_4.addWidget(self.labelSensor5, 1, 4, 1, 1)
        self.labelSensor6 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor6.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor6.setText("")
        self.labelSensor6.setObjectName("labelSensor6")
        self.gridLayout_4.addWidget(self.labelSensor6, 1, 5, 1, 1)
        self.labelSensor7 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor7.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor7.setText("")
        self.labelSensor7.setObjectName("labelSensor7")
        self.gridLayout_4.addWidget(self.labelSensor7, 1, 6, 1, 1)
        self.labelSensor8 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor8.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor8.setText("")
        self.labelSensor8.setObjectName("labelSensor8")
        self.gridLayout_4.addWidget(self.labelSensor8, 1, 7, 1, 1)
        self.labelSensor9 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor9.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor9.setText("")
        self.labelSensor9.setObjectName("labelSensor9")
        self.gridLayout_4.addWidget(self.labelSensor9, 1, 8, 1, 1)
        self.labelSensor10 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor10.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor10.setText("")
        self.labelSensor10.setObjectName("labelSensor10")
        self.gridLayout_4.addWidget(self.labelSensor10, 1, 9, 1, 1)
        self.labelSensor11 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor11.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor11.setText("")
        self.labelSensor11.setObjectName("labelSensor11")
        self.gridLayout_4.addWidget(self.labelSensor11, 1, 10, 1, 1)
        self.labelSensor12 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor12.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor12.setText("")
        self.labelSensor12.setObjectName("labelSensor12")
        self.gridLayout_4.addWidget(self.labelSensor12, 1, 11, 1, 1)
        self.labelSensor13 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor13.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor13.setText("")
        self.labelSensor13.setObjectName("labelSensor13")
        self.gridLayout_4.addWidget(self.labelSensor13, 1, 12, 1, 1)
        self.labelSensor14 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor14.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor14.setText("")
        self.labelSensor14.setObjectName("labelSensor14")
        self.gridLayout_4.addWidget(self.labelSensor14, 1, 13, 1, 1)
        self.labelSensor15 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor15.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor15.setText("")
        self.labelSensor15.setObjectName("labelSensor15")
        self.gridLayout_4.addWidget(self.labelSensor15, 1, 14, 1, 1)
        self.labelSensor16 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor16.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor16.setText("")
        self.labelSensor16.setObjectName("labelSensor16")
        self.gridLayout_4.addWidget(self.labelSensor16, 1, 15, 1, 1)
        self.labelSensor17 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor17.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor17.setText("")
        self.labelSensor17.setObjectName("labelSensor17")
        self.gridLayout_4.addWidget(self.labelSensor17, 1, 16, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.layoutWidget)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.gridLayout_4.addWidget(self.label_78, 2, 0, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.layoutWidget)
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.gridLayout_4.addWidget(self.label_86, 2, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.layoutWidget)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.gridLayout_4.addWidget(self.label_76, 2, 2, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.layoutWidget)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.gridLayout_4.addWidget(self.label_66, 2, 3, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.layoutWidget)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout_4.addWidget(self.label_60, 2, 4, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.layoutWidget)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_4.addWidget(self.label_62, 2, 5, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.layoutWidget)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.gridLayout_4.addWidget(self.label_65, 2, 6, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_4.addWidget(self.label_55, 2, 7, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.layoutWidget)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_4.addWidget(self.label_68, 2, 8, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.layoutWidget)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.gridLayout_4.addWidget(self.label_85, 2, 9, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_4.addWidget(self.label_63, 2, 10, 1, 1)
        self.labelSensor18 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor18.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor18.setText("")
        self.labelSensor18.setObjectName("labelSensor18")
        self.gridLayout_4.addWidget(self.labelSensor18, 3, 0, 1, 1)
        self.labelSensor19 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor19.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor19.setText("")
        self.labelSensor19.setObjectName("labelSensor19")
        self.gridLayout_4.addWidget(self.labelSensor19, 3, 1, 1, 1)
        self.labelSensor20 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor20.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor20.setText("")
        self.labelSensor20.setObjectName("labelSensor20")
        self.gridLayout_4.addWidget(self.labelSensor20, 3, 2, 1, 1)
        self.labelSensor21 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor21.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor21.setText("")
        self.labelSensor21.setObjectName("labelSensor21")
        self.gridLayout_4.addWidget(self.labelSensor21, 3, 3, 1, 1)
        self.labelSensor22 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor22.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor22.setText("")
        self.labelSensor22.setObjectName("labelSensor22")
        self.gridLayout_4.addWidget(self.labelSensor22, 3, 4, 1, 1)
        self.labelSensor23 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor23.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor23.setText("")
        self.labelSensor23.setObjectName("labelSensor23")
        self.gridLayout_4.addWidget(self.labelSensor23, 3, 5, 1, 1)
        self.labelSensor24 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor24.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor24.setText("")
        self.labelSensor24.setObjectName("labelSensor24")
        self.gridLayout_4.addWidget(self.labelSensor24, 3, 6, 1, 1)
        self.labelSensor25 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor25.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor25.setText("")
        self.labelSensor25.setObjectName("labelSensor25")
        self.gridLayout_4.addWidget(self.labelSensor25, 3, 7, 1, 1)
        self.labelSensor26 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor26.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor26.setText("")
        self.labelSensor26.setObjectName("labelSensor26")
        self.gridLayout_4.addWidget(self.labelSensor26, 3, 8, 1, 1)
        self.labelSensor27 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor27.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor27.setText("")
        self.labelSensor27.setObjectName("labelSensor27")
        self.gridLayout_4.addWidget(self.labelSensor27, 3, 9, 1, 1)
        self.labelSensor28 = QtWidgets.QLabel(self.layoutWidget)
        self.labelSensor28.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.labelSensor28.setText("")
        self.labelSensor28.setObjectName("labelSensor28")
        self.gridLayout_4.addWidget(self.labelSensor28, 3, 10, 1, 1)
        self.layoutWidget.raise_()
        self.label_58.raise_()
        self.ButtonGetSensorState.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.BoxServoMotor = QtWidgets.QGroupBox(self.groupBoxContorl)
        self.BoxServoMotor.setGeometry(QtCore.QRect(10, 70, 751, 341))
        self.BoxServoMotor.setObjectName("BoxServoMotor")
        self.ButtonBurningStart = QtWidgets.QPushButton(self.BoxServoMotor)
        self.ButtonBurningStart.setGeometry(QtCore.QRect(590, 180, 131, 31))
        self.ButtonBurningStart.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonBurningStart.setObjectName("ButtonBurningStart")
        self.label_7 = QtWidgets.QLabel(self.BoxServoMotor)
        self.label_7.setGeometry(QtCore.QRect(590, 140, 81, 31))
        self.label_7.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.EditBurnTimes = QtWidgets.QLineEdit(self.BoxServoMotor)
        self.EditBurnTimes.setGeometry(QtCore.QRect(680, 140, 41, 31))
        self.EditBurnTimes.setAlignment(QtCore.Qt.AlignCenter)
        self.EditBurnTimes.setObjectName("EditBurnTimes")
        self.groupBox_2 = QtWidgets.QGroupBox(self.BoxServoMotor)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 291, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.EditServoSpeed = QtWidgets.QLineEdit(self.groupBox_2)
        self.EditServoSpeed.setGeometry(QtCore.QRect(80, 11, 66, 31))
        self.EditServoSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.EditServoSpeed.setObjectName("EditServoSpeed")
        self.EditAbsolute = QtWidgets.QLineEdit(self.groupBox_2)
        self.EditAbsolute.setGeometry(QtCore.QRect(80, 51, 66, 31))
        self.EditAbsolute.setAlignment(QtCore.Qt.AlignCenter)
        self.EditAbsolute.setObjectName("EditAbsolute")
        self.label_165 = QtWidgets.QLabel(self.groupBox_2)
        self.label_165.setGeometry(QtCore.QRect(30, 99, 51, 16))
        self.label_165.setObjectName("label_165")
        self.label_161 = QtWidgets.QLabel(self.groupBox_2)
        self.label_161.setGeometry(QtCore.QRect(30, 60, 51, 16))
        self.label_161.setObjectName("label_161")
        self.ButtonAbsoluteMove = QtWidgets.QPushButton(self.groupBox_2)
        self.ButtonAbsoluteMove.setGeometry(QtCore.QRect(160, 53, 111, 31))
        self.ButtonAbsoluteMove.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonAbsoluteMove.setObjectName("ButtonAbsoluteMove")
        self.EditRelative = QtWidgets.QLineEdit(self.groupBox_2)
        self.EditRelative.setGeometry(QtCore.QRect(80, 90, 66, 31))
        self.EditRelative.setAlignment(QtCore.Qt.AlignCenter)
        self.EditRelative.setObjectName("EditRelative")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 19, 61, 20))
        self.label_4.setObjectName("label_4")
        self.ButtonRelativeMove = QtWidgets.QPushButton(self.groupBox_2)
        self.ButtonRelativeMove.setGeometry(QtCore.QRect(160, 90, 111, 31))
        self.ButtonRelativeMove.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonRelativeMove.setObjectName("ButtonRelativeMove")
        self.ButtonSetServoSpeed = QtWidgets.QPushButton(self.groupBox_2)
        self.ButtonSetServoSpeed.setGeometry(QtCore.QRect(160, 11, 111, 31))
        self.ButtonSetServoSpeed.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonSetServoSpeed.setObjectName("ButtonSetServoSpeed")
        self.EditRelative_X = QtWidgets.QLineEdit(self.groupBox_2)
        self.EditRelative_X.setGeometry(QtCore.QRect(80, 207, 66, 31))
        self.EditRelative_X.setAlignment(QtCore.Qt.AlignCenter)
        self.EditRelative_X.setObjectName("EditRelative_X")
        self.ButtonAbsoluteMove_X = QtWidgets.QPushButton(self.groupBox_2)
        self.ButtonAbsoluteMove_X.setGeometry(QtCore.QRect(160, 170, 111, 31))
        self.ButtonAbsoluteMove_X.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonAbsoluteMove_X.setObjectName("ButtonAbsoluteMove_X")
        self.ButtonRelativeMove_X = QtWidgets.QPushButton(self.groupBox_2)
        self.ButtonRelativeMove_X.setGeometry(QtCore.QRect(160, 207, 111, 31))
        self.ButtonRelativeMove_X.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonRelativeMove_X.setObjectName("ButtonRelativeMove_X")
        self.label_166 = QtWidgets.QLabel(self.groupBox_2)
        self.label_166.setGeometry(QtCore.QRect(30, 216, 51, 16))
        self.label_166.setObjectName("label_166")
        self.label_162 = QtWidgets.QLabel(self.groupBox_2)
        self.label_162.setGeometry(QtCore.QRect(30, 177, 51, 16))
        self.label_162.setObjectName("label_162")
        self.EditAbsolute_X = QtWidgets.QLineEdit(self.groupBox_2)
        self.EditAbsolute_X.setGeometry(QtCore.QRect(80, 168, 66, 31))
        self.EditAbsolute_X.setAlignment(QtCore.Qt.AlignCenter)
        self.EditAbsolute_X.setObjectName("EditAbsolute_X")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(20, 140, 61, 16))
        self.label_15.setObjectName("label_15")
        self.ButtonSetServoSpeed_X = QtWidgets.QPushButton(self.groupBox_2)
        self.ButtonSetServoSpeed_X.setGeometry(QtCore.QRect(160, 132, 111, 31))
        self.ButtonSetServoSpeed_X.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonSetServoSpeed_X.setObjectName("ButtonSetServoSpeed_X")
        self.EditServoSpeed_X = QtWidgets.QLineEdit(self.groupBox_2)
        self.EditServoSpeed_X.setGeometry(QtCore.QRect(80, 132, 66, 31))
        self.EditServoSpeed_X.setAlignment(QtCore.Qt.AlignCenter)
        self.EditServoSpeed_X.setObjectName("EditServoSpeed_X")
        self.ButtonMotorValidation = QtWidgets.QPushButton(self.BoxServoMotor)
        self.ButtonMotorValidation.setGeometry(QtCore.QRect(590, 70, 131, 31))
        self.ButtonMotorValidation.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonMotorValidation.setObjectName("ButtonMotorValidation")
        self.label_11 = QtWidgets.QLabel(self.BoxServoMotor)
        self.label_11.setGeometry(QtCore.QRect(590, 30, 81, 31))
        self.label_11.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.EditSweepTimes = QtWidgets.QLineEdit(self.BoxServoMotor)
        self.EditSweepTimes.setGeometry(QtCore.QRect(680, 30, 41, 31))
        self.EditSweepTimes.setAlignment(QtCore.Qt.AlignCenter)
        self.EditSweepTimes.setObjectName("EditSweepTimes")
        self.BtDutLock_2 = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtDutLock_2.setGeometry(QtCore.QRect(360, 140, 93, 28))
        self.BtDutLock_2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtDutLock_2.setObjectName("BtDutLock_2")
        self.BtDutUnlock_2 = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtDutUnlock_2.setGeometry(QtCore.QRect(470, 140, 93, 28))
        self.BtDutUnlock_2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtDutUnlock_2.setObjectName("BtDutUnlock_2")
        self.ButtonCylinderIN_1 = QtWidgets.QPushButton(self.BoxServoMotor)
        self.ButtonCylinderIN_1.setGeometry(QtCore.QRect(360, 20, 102, 29))
        self.ButtonCylinderIN_1.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonCylinderIN_1.setObjectName("ButtonCylinderIN_1")
        self.BtUSBLock = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtUSBLock.setGeometry(QtCore.QRect(360, 180, 93, 28))
        self.BtUSBLock.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtUSBLock.setObjectName("BtUSBLock")
        self.BtUSBLock_2 = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtUSBLock_2.setGeometry(QtCore.QRect(360, 220, 93, 28))
        self.BtUSBLock_2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtUSBLock_2.setObjectName("BtUSBLock_2")
        self.ButtonCylinderIN_2 = QtWidgets.QPushButton(self.BoxServoMotor)
        self.ButtonCylinderIN_2.setGeometry(QtCore.QRect(360, 60, 102, 30))
        self.ButtonCylinderIN_2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonCylinderIN_2.setObjectName("ButtonCylinderIN_2")
        self.BtDutLock = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtDutLock.setGeometry(QtCore.QRect(360, 101, 93, 28))
        self.BtDutLock.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtDutLock.setObjectName("BtDutLock")
        self.ButtonCylinderOUT_1 = QtWidgets.QPushButton(self.BoxServoMotor)
        self.ButtonCylinderOUT_1.setGeometry(QtCore.QRect(468, 20, 102, 29))
        self.ButtonCylinderOUT_1.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonCylinderOUT_1.setObjectName("ButtonCylinderOUT_1")
        self.ButtonCylinderOUT_2 = QtWidgets.QPushButton(self.BoxServoMotor)
        self.ButtonCylinderOUT_2.setGeometry(QtCore.QRect(468, 60, 102, 30))
        self.ButtonCylinderOUT_2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonCylinderOUT_2.setObjectName("ButtonCylinderOUT_2")
        self.BtDutUnlock = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtDutUnlock.setGeometry(QtCore.QRect(468, 101, 93, 28))
        self.BtDutUnlock.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtDutUnlock.setObjectName("BtDutUnlock")
        self.BtUSBUnlock = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtUSBUnlock.setGeometry(QtCore.QRect(468, 180, 93, 28))
        self.BtUSBUnlock.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtUSBUnlock.setObjectName("BtUSBUnlock")
        self.BtUSBUnlock_2 = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtUSBUnlock_2.setGeometry(QtCore.QRect(468, 220, 93, 28))
        self.BtUSBUnlock_2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtUSBUnlock_2.setObjectName("BtUSBUnlock_2")
        self.BtPower_Up = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtPower_Up.setGeometry(QtCore.QRect(362, 260, 93, 28))
        self.BtPower_Up.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtPower_Up.setObjectName("BtPower_Up")
        self.BtPower_Down = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtPower_Down.setGeometry(QtCore.QRect(470, 260, 93, 28))
        self.BtPower_Down.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtPower_Down.setObjectName("BtPower_Down")
        self.label_16 = QtWidgets.QLabel(self.BoxServoMotor)
        self.label_16.setGeometry(QtCore.QRect(590, 140, 81, 31))
        self.label_16.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.BoxServoMotor)
        self.label_17.setGeometry(QtCore.QRect(590, 30, 81, 31))
        self.label_17.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.ButtonMotorValidation_2 = QtWidgets.QPushButton(self.BoxServoMotor)
        self.ButtonMotorValidation_2.setGeometry(QtCore.QRect(590, 70, 131, 31))
        self.ButtonMotorValidation_2.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonMotorValidation_2.setObjectName("ButtonMotorValidation_2")
        self.EditSweepTimes_2 = QtWidgets.QLineEdit(self.BoxServoMotor)
        self.EditSweepTimes_2.setGeometry(QtCore.QRect(680, 30, 41, 31))
        self.EditSweepTimes_2.setAlignment(QtCore.Qt.AlignCenter)
        self.EditSweepTimes_2.setObjectName("EditSweepTimes_2")
        self.textEditPassword = QtWidgets.QLineEdit(self.BoxServoMotor)
        self.textEditPassword.setGeometry(QtCore.QRect(590, 230, 131, 31))
        self.textEditPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.textEditPassword.setObjectName("textEditPassword")
        self.BtnPassword = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtnPassword.setGeometry(QtCore.QRect(590, 270, 131, 31))
        self.BtnPassword.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtnPassword.setObjectName("BtnPassword")
        self.BtUSB_Off = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtUSB_Off.setGeometry(QtCore.QRect(470, 300, 91, 28))
        self.BtUSB_Off.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtUSB_Off.setObjectName("BtUSB_Off")
        self.BtUSB_On = QtWidgets.QPushButton(self.BoxServoMotor)
        self.BtUSB_On.setGeometry(QtCore.QRect(364, 300, 91, 28))
        self.BtUSB_On.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtUSB_On.setObjectName("BtUSB_On")
        self.label_10 = QtWidgets.QLabel(self.groupBoxContorl)
        self.label_10.setGeometry(QtCore.QRect(10, 670, 171, 41))
        self.label_10.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.labelError = QtWidgets.QLabel(self.groupBoxContorl)
        self.labelError.setGeometry(QtCore.QRect(200, 670, 601, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.labelError.setFont(font)
        self.labelError.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelError.setText("")
        self.labelError.setAlignment(QtCore.Qt.AlignCenter)
        self.labelError.setObjectName("labelError")
        self.ButtonSignalReset = QtWidgets.QPushButton(self.groupBoxContorl)
        self.ButtonSignalReset.setGeometry(QtCore.QRect(350, 20, 91, 31))
        self.ButtonSignalReset.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonSignalReset.setObjectName("ButtonSignalReset")
        self.BtSetMotorStop = QtWidgets.QPushButton(self.groupBoxContorl)
        self.BtSetMotorStop.setGeometry(QtCore.QRect(460, 20, 91, 31))
        self.BtSetMotorStop.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.BtSetMotorStop.setObjectName("BtSetMotorStop")
        self.radioNQ = QtWidgets.QRadioButton(self.groupBoxContorl)
        self.radioNQ.setGeometry(QtCore.QRect(260, 20, 82, 17))
        self.radioNQ.setObjectName("radioNQ")
        self.radioGQ = QtWidgets.QRadioButton(self.groupBoxContorl)
        self.radioGQ.setGeometry(QtCore.QRect(260, 40, 82, 17))
        self.radioGQ.setObjectName("radioGQ")
        self.ButtonCloseDoor = QtWidgets.QPushButton(self.groupBoxContorl)
        self.ButtonCloseDoor.setGeometry(QtCore.QRect(580, 20, 91, 31))
        self.ButtonCloseDoor.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonCloseDoor.setObjectName("ButtonCloseDoor")
        self.ButtonOpenDoor = QtWidgets.QPushButton(self.groupBoxContorl)
        self.ButtonOpenDoor.setGeometry(QtCore.QRect(680, 20, 81, 31))
        self.ButtonOpenDoor.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.ButtonOpenDoor.setObjectName("ButtonOpenDoor")
        self.BoxServoMotor.raise_()
        self.BtOpenportContorl.raise_()
        self.BtCloseportContorl.raise_()
        self.tabWidget.raise_()
        self.label_10.raise_()
        self.labelError.raise_()
        self.ButtonSignalReset.raise_()
        self.BtSetMotorStop.raise_()
        self.radioNQ.raise_()
        self.radioGQ.raise_()
        self.ButtonCloseDoor.raise_()
        self.ButtonOpenDoor.raise_()
        self.groupBoxContorl.raise_()
        self.groupBoxShow.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "G71-N71 Developed by Bojay"))
        self.groupBoxShow.setTitle(_translate("Form", "Temperature Show"))
        self.BtOpenportShow.setText(_translate("Form", "OpenSerial"))
        self.BtCloseportShow.setText(_translate("Form", "CloseSerial"))
        self.BtSetTargetTemperature.setText(_translate("Form", "SetTargetTemp(CH1)"))
        self.BtAutomaticGet.setText(_translate("Form", "Start Automatic"))
        self.label_2.setText(_translate("Form", " Target temperature(CH1）"))
        self.label_8.setText(_translate("Form", " Target temperature(CH2）"))
        self.label_9.setText(_translate("Form", " Target temperature(CH3）"))
        self.label.setText(_translate("Form", " indoor temperature(CH4)"))
        self.label_3.setText(_translate("Form", " temperature different"))
        self.BtAutomaticStop.setText(_translate("Form", "Stop Automatic"))
        self.BtTemperatureValidation.setText(_translate("Form", "Temperature Validation"))
        self.label_5.setText(_translate("Form", "RAngle_x"))
        self.label_6.setText(_translate("Form", "RAngle_y"))
        self.BtSetToZero.setText(_translate("Form", "SetTo_R Zero"))
        self.BtAngleValidation.setText(_translate("Form", "Angle Validation"))
        self.BtStepValidation.setText(_translate("Form", "Step Validation"))
        self.label_12.setText(_translate("Form", "Times"))
        self.label_13.setText(_translate("Form", "XAngle_y"))
        self.label_14.setText(_translate("Form", "XAngle_x"))
        self.BtSetToZero_X.setText(_translate("Form", "SetTo_X Zero"))
        self.groupBoxContorl.setTitle(_translate("Form", "MCU Control"))
        self.BtOpenportContorl.setText(_translate("Form", "OpenMCU"))
        self.BtCloseportContorl.setText(_translate("Form", "CloseMCU"))
        self.label_58.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Sensor Getting:</span></p></body></html>"))
        self.ButtonGetSensorState.setText(_translate("Form", "get"))
        self.label_56.setText(_translate("Form", "X00"))
        self.label_69.setText(_translate("Form", "X01"))
        self.label_79.setText(_translate("Form", "X02"))
        self.label_50.setText(_translate("Form", "X03"))
        self.label_61.setText(_translate("Form", "X04"))
        self.label_67.setText(_translate("Form", "X05"))
        self.label_51.setText(_translate("Form", "X06"))
        self.label_77.setText(_translate("Form", "X07"))
        self.label_75.setText(_translate("Form", "X10"))
        self.label_64.setText(_translate("Form", "X11"))
        self.label_54.setText(_translate("Form", "X12"))
        self.label_82.setText(_translate("Form", "X13"))
        self.label_83.setText(_translate("Form", "X14"))
        self.label_53.setText(_translate("Form", "X15"))
        self.label_71.setText(_translate("Form", "X16"))
        self.label_84.setText(_translate("Form", "X17"))
        self.label_81.setText(_translate("Form", "X20"))
        self.label_78.setText(_translate("Form", "X21"))
        self.label_86.setText(_translate("Form", "X22"))
        self.label_76.setText(_translate("Form", "X23"))
        self.label_66.setText(_translate("Form", "X24"))
        self.label_60.setText(_translate("Form", "X25"))
        self.label_62.setText(_translate("Form", "X26"))
        self.label_65.setText(_translate("Form", "X27"))
        self.label_55.setText(_translate("Form", "X30"))
        self.label_68.setText(_translate("Form", "X31"))
        self.label_85.setText(_translate("Form", "X32"))
        self.label_63.setText(_translate("Form", "X33"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Input"))
        self.BoxServoMotor.setTitle(_translate("Form", "Servo Motor"))
        self.ButtonBurningStart.setText(_translate("Form", "BurningStart"))
        self.label_7.setText(_translate("Form", "BurnTimes"))
        self.groupBox_2.setTitle(_translate("Form", "Axis"))
        self.label_165.setText(_translate("Form", "R_Axis"))
        self.label_161.setText(_translate("Form", "R_Axis"))
        self.ButtonAbsoluteMove.setText(_translate("Form", "Absolute Move"))
        self.label_4.setText(_translate("Form", "R_speed"))
        self.ButtonRelativeMove.setText(_translate("Form", "Relative Move"))
        self.ButtonSetServoSpeed.setText(_translate("Form", "SetSpeed"))
        self.ButtonAbsoluteMove_X.setText(_translate("Form", "Absolute Move"))
        self.ButtonRelativeMove_X.setText(_translate("Form", "Relative Move"))
        self.label_166.setText(_translate("Form", "X_Axis"))
        self.label_162.setText(_translate("Form", "X_Axis"))
        self.label_15.setText(_translate("Form", "X_speed"))
        self.ButtonSetServoSpeed_X.setText(_translate("Form", "SetSpeed"))
        self.ButtonMotorValidation.setText(_translate("Form", "Motor Validation"))
        self.label_11.setText(_translate("Form", "Sweep Times"))
        self.BtDutLock_2.setText(_translate("Form", "Dut2Lock"))
        self.BtDutUnlock_2.setText(_translate("Form", "Dut2Unlock"))
        self.ButtonCylinderIN_1.setText(_translate("Form", "CylinderIN_1"))
        self.BtUSBLock.setText(_translate("Form", "USB1Lock"))
        self.BtUSBLock_2.setText(_translate("Form", "USB2Lock"))
        self.ButtonCylinderIN_2.setText(_translate("Form", "CylinderIN_2"))
        self.BtDutLock.setText(_translate("Form", "Dut1Lock"))
        self.ButtonCylinderOUT_1.setText(_translate("Form", "CylinderOUT_1"))
        self.ButtonCylinderOUT_2.setText(_translate("Form", "CylinderOUT_2"))
        self.BtDutUnlock.setText(_translate("Form", "Dut1Unlock"))
        self.BtUSBUnlock.setText(_translate("Form", "USB1Unlock"))
        self.BtUSBUnlock_2.setText(_translate("Form", "USB2Unlock"))
        self.BtPower_Up.setText(_translate("Form", "Power Up"))
        self.BtPower_Down.setText(_translate("Form", "Power Down"))
        self.label_16.setText(_translate("Form", "BurnTimes"))
        self.label_17.setText(_translate("Form", "Sweep Times"))
        self.ButtonMotorValidation_2.setText(_translate("Form", "Motor Validation"))
        self.BtnPassword.setText(_translate("Form", "Password"))
        self.BtUSB_Off.setText(_translate("Form", "USB Off"))
        self.BtUSB_On.setText(_translate("Form", "USB On"))
        self.label_10.setText(_translate("Form", "Message"))
        self.ButtonSignalReset.setText(_translate("Form", "SignalReset"))
        self.BtSetMotorStop.setText(_translate("Form", "SetMotorStop"))
        self.radioNQ.setText(_translate("Form", "NQ"))
        self.radioGQ.setText(_translate("Form", "GQ"))
        self.ButtonCloseDoor.setText(_translate("Form", "CloseDoor"))
        self.ButtonOpenDoor.setText(_translate("Form", "OpenDoor"))
